version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - 5775:5775/udp # accept zipkin.thrift over compact thrift protocol
      - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # serve configs
      - 16686:16686 # serve frontend
      - 14268:14268 # accept jaeger.thrift directly from clients
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    ports:
      - 2135:2135
      - 8765:8765
      - 2136:2136
    environment:
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
      - GRPC_TLS_PORT=2135 
      - GRPC_PORT=2136 
      - MON_PORT=8765
    volumes:
      - ydb_data:/ydb_data
      - ydb_certs:/ydb_certs
volumes:
  ydb_data:
    driver: local
  ydb_certs:
    driver: local
